### ISSUE TITLE
When showing by heart level, toggling off and on allows showing NPCs who don't meet the conditions.

### ISSUE THREAD

**Issue by torrentails** [Bouhm/stardew-valley-mods#10]
Currently I have the configs set so that only NPCs with whom I have a relationship level of 2 or greater hearts will show up on the map but I found that if I toggle the check mark off then on again of an NPC with whom I don't yet have 2 hearts, the mod then shows me that NPC on the map, ignoring the settings in the config file.

My preferred fix for this would be to grey out the check box for NPCs who don't meet the requirements. (The same way that it's greyed out for NPCs that the player hasn't met yet.)

**Comment by Bouhm** [comment]
I followed the steps and was unable to reproduce this bug. 

There is a separate option to show hidden NPCs instead of not rendering them at all. Visually, it's not great but it was the best I could do with the limitations of XNA.
