### ISSUE TITLE
[NPCMapLocations] Hide minimap in dungeons automatically

### ISSUE THREAD

**Issue by NightFright2k19** [Bouhm/stardew-valley-mods#103]
I wasn't even aware that the game shows the level number in the top left corner of the screen when you are in the Mines, Skull Cavern etc. because my minimap was hiding the display. 

It would be great to have an option which automatically hides the minimap when in dungeons in general (it's rather useless there, anyway).

**Comment by NightFright2k19** [comment]
*EDIT*
OK, I just saw there is the nifty option _MinimapExclusions_ which basically does just that.

**Comment by NightFright2k19** [comment]
It would still be good to know what the MinimapExclusions entry would have to look like for all dungeons, though,

**Comment by Pathoschild** [comment]
@NightFright2k19 This will exclude all mines and the volcano dungeon:
```js
"MinimapExclusions": [ "Mines", "SkullCavern", "VolcanoDungeon" ],
```
