### ISSUE TITLE
[NPC Map Locations] Minimap not restored after leaving excluded zone

### ISSUE THREAD

**Issue by NightFright2k19** [bouhm/stardew-valley-mods#104]
Using: NPC Map Locations v2.9.3

I have set up three exceptions for showing the minimap in globals.json:
`"MinimapExclusions": [ "Mine", "SkullCave", "VolcanoDungeon" ],`

While the minimap is correctly hidden when entering those areas, it is not turned on again when you return to an area that is not excluded. 

I thought that the above option would make it so that if the minimap is enabled, it would always be drawn except in those places you specify.

**Comment by Pathoschild** [comment]
This should be fixed in NPC Map Locations 2.10.0 and later. Thanks for reporting it!
