### ISSUE TITLE
Update for version 1.5 of SMAPI mobile

### ISSUE THREAD

**Issue by hellboy911** [bouhm/stardew-valley-mods#112]
With SV mobile update 1.5 also updated SMAPI mobile which caused the NPC Map Location mod to stop working. I was wondering if there will be any update for mobile devices?

**Comment by Pathoschild** [comment]
Hi! That's a bug in SMAPI for Android's rewriters. It's already been [reported to the maintainer](https://github.com/ZaneYork/SMAPI-Android-Installer/issues/302), so hopefully it'll be fixed in upcoming SMAPI updates on Android.
