### ISSUE TITLE
Map marker cropping issues with reskinned NPCs

### ISSUE THREAD

**Issue by Manlibear** [Bouhm/stardew-valley-mods#21]
I'm using Adarins Girl Mod, it replaces certain male NPCs with females. This causes an issue with your mod as their sprites have changed size so on the map screen their marker/face is half cropped off.

Would it be possible to bring `markerCrop` out into a config file rather than a constant? Or perhaps even just allow for overrides to be specified in the config file. I grabbed your source and tried to build my own, but when I run the mod in the game I get an error regarding a missing asset called map.

If I can help in any other way, just give me a shout

**Comment by Bouhm** [comment]
Hiya, the config file actually has exactly what you're looking for!

Find  "villagerCrop": { } and adjust the cropping like so. These are the numbers that should work for the Adarins mod.
```
"villagerCrop": {
    "Alex": 3,
    "Elliott": 2,
    "Harvey": 5,
    "Sam": 2,
    "Sebastian": 3
},
```

I'm about to do a release for a big update, so you can install all the files you need from releases.

**Comment by Manlibear** [comment]
Thank you very much!
