### ISSUE TITLE
Japanese, Chinese, Russian, Spanish, Portuguese, & German Translations

### ISSUE THREAD

**Issue by Bouhm** [Bouhm/stardew-valley-mods#4]
With official Japanese, Chinese, Russian, Spanish, Portuguese, German and possibly Thai translations of Stardew Valley planned this month, I am looking to add translations to this mod. Please let me know if you are know any of these languages and are interested in helping out. Thanks!

The translations do not have to be direct/literal word-for-word translations; feel free to phrase it however you see fit based on what the settings actually do. It just has to be concise and intuitive.

Text: http://pastebin.com/S6urxKQz

**Comment by HappyHackingNinja** [comment]
Its Chinese version:
* Names Tooltip Placement
  -  人名提示顯示位置

* Villagers Tooltip Placement
  - 村民提示顯示位置

* Above location tooltip
  - 於所在位置提示之上

* Below location tooltip
  - 於所在位置提示之下

* Bottom-left corner
  - 於畫面左下角處

* Immersion Settings
  - 沉浸式設定

* Always show villagers
  - 總是顯示所有村民

* Show villagers player has talked to
  - 只顯示談話過的村民

* Hide villagers player has talked to
  - 隱藏談話過的村民

* Only show villagers in player's location
  - 只顯示位於玩家所在區域的村民

* Only show villagers within specified heart level
  - 只顯示特定好感度的村民

* Minimum heart level
  - 最小好感度

* Maximum heart level
  - 最大好感度

* Extra Settings
  - 額外設定

* Show Extra Settings
  - 額外顯示設定

* Mark villagers with daily quest or birthday
  - 標記與日常任務相關或當天生日的村民

* Show Traveling Merchant
  - 顯示旅行商人

* Include/Exclude Villagers
  - 包含/排除 村民

- - - 

By the way, could you add an option like " Mark villagers has talked to" or "Display villagers has talked to as grayscale"? It'll be of great help to me.

**Comment by Bouhm** [comment]
Thank you for the translations! And I'll look into adding that in the next update.

**Comment by josemscnogueira** [comment]
**Names Tooltip Placement**
    Posicionamento dos nomes das dicas
**Above Location Tooltip**
    Localização superior das dicas
**Below Location Tooltip**
    Localização inferior das dicas
**Bottom-Left Corner**
    Canto inferior esquerdo
**Immersion Settings**
    Opções de imersão
**Always Show Villagers**
    Sempre mostrar aldeões
**Show Villagers Player Has Talked To**
    Mostrar aldeões com quem o jogador tenha falado
**Hide Villagers Player Has Talked To**
    Esconder aldeões com quem o jogador tenha falado
**Only Show Villagers in Player's Location**
   Mostrar apenas aldeões na mesma localização do jogador
**Only Show Villagers Within Specified Heart Level**
   Mostrar apenas aldeões com um determinado nível de corações
**Minimum Heart Level**
    Nível mínimo de corações
**Maximum Heart Level**
    Nível máximo de corações
**Extra Settings**
    Opções extra
**Mark Villagers With Daily Quest or Birthday**
    Marcar aldeões com tarefas diárias ou aniversários
**Show Hidden Villagers**
    Mostrar aldeões ocultos
**Show Traveling Merchant**
    Mostrar vendedor viajante
**Include/Exclude Villagers**
    Incluir/Excluir aldeões

If you need more help contact me directly.

Cheers

**Comment by Bouhm** [comment]
Thank you very much! :)

**Comment by simplefield** [comment]
### Japanese translations:

- Names Tooltip Placement
  - 名前の表示位置
- Above Location Tooltip
  - 場所の上
- Below Location Tooltip
  - 場所の下
- Bottom-Left Corner
  - マップの左下
- Immersion Settings
  - 注目設定
- Always Show Villagers
  - 住人を常に表示する
- Show Villagers Player Has Talked To
  - プレイヤーと話した住人を表示する
- Hide Villagers Player Has Talked To
  - プレイヤーと話した住人を非表示にする
- Only Show Villagers in Player's Location
  - プレイヤーがいる地区の住人だけを表示する
- Only Show Villagers Within Specified Heart Level
  - 特定の好感度の住人だけを表示する
- Minimum Heart Level
  - 最小好感度
- Maximum Heart Level
  - 最大好感度
- Extra Settings
  - その他の設定
- Mark Villagers With Daily Quest or Birthday
  - デイリークエストや誕生日の住人にマークを付ける
- Show Hidden Villagers
  - 隠された住人を表示する
- Show Traveling Merchant
  - 行商人を表示する
- Include/Exclude Villagers
  - 住人の表示/非表示

This mod is so great helpful to me :)

**Comment by Bouhm** [comment]
Thank you so much! :)
