### ISSUE TITLE
Translations for Turkish

### ISSUE THREAD

**Issue by Bouhm** [Bouhm/stardew-valley-mods#47]
https://www.nexusmods.com/stardewvalley/articles/101

**Text to be translated:**
Minimap
Enabled
Minimap width
Minimap height
Settings
Always show villagers
Show villagers player has talked to
Hide villagers player has talked to
Only show villagers in player's location
Only show villagers within heart level
Minimum heart level
Maximum heart level
Show quests or birthdays
Show hidden villagers
Show traveling merchant
Include/Exclude villagers

**Comment by LunaLuti** [comment]
{
"minimap.label": "Mini harita",
"minimap.option1": "Etkin",
"minimap.plusMinus1": "Mini harita genişliği",
"minimap.plusMinus2": "Mini harita uzunluğu",
"immersion.label": "Ayarlar:",
"immersion.option1": "Tüm köylüleri göster",
"immersion.option2": "Oyuncunun konuştuğu köylüleri göster",
"immersion.option3": "Oyuncunun konuştuğu köylüleri gizle",
"immersion.option4": "Sadece oyuncunun bölgesindeki köylüleri göster",
"immersion.option5": "Sadece belirli kalp seviyesi içindeki köylüleri göster",
"immersion.slider1": "En az kalp seviyesi",
"immersion.slider2": "En fazla kalp seviyesi",
"extra.label": "Ekstra ayarlar:",
"extra.option1": "Görevleri ya da doğum günlerini göster",
"extra.option2": "Gizli köylüleri göster",
"extra.option3": "Gezgin tüccarı göster", 
"villagers.label": "Köylüleri ekle/çıkar:"
}

Extras: 
Always show villagers - Her zaman köylüleri göster
Show hidden villagers - Gizlenmiş köylüleri göster

**Comment by Bouhm** [comment]
Thank you very much!
