### ISSUE TITLE
Using mutiple files in GitHub release allows multiple mods in one repo

### ISSUE THREAD

**Issue by Crystal-RainSlide** [Bouhm/stardew-valley-mods#50]
If you would like to continue make GitHub Releases as a mirror to the nexusmod page, you may release mutiple files to match the mods in this repo, or even put releases in another branch so others can download them in one clone command/file via GitHub's button.

This is great for those who don't have a nexusmod account, but it's your choice~

**Comment by Pathoschild** [comment]
(A Nexus account is free; you just need to scroll past the paid plans and click the 'create account' button.)

**Comment by Bouhm** [comment]
Added NPC Map Locations to releases. For now, I'll just be doing NPC Map Location releases.
