### ISSUE TITLE
NPC Map Locations 2.5.1 for SVE Install Error

### ISSUE THREAD

**Issue by dehrk** [Bouhm/stardew-valley-mods#54]
When trying to install the mod through Vortex, I'm getting the attached error.
![vortex-error](https://user-images.githubusercontent.com/4471959/66879943-9d011880-ef8e-11e9-8767-044ccc5efff1.png)

**Comment by Bouhm** [comment]
Could you try reporting the bug through Vortex (three dots at top-right and 'Send Feedback')? At the moment there is no information on how I can resolve this issue on my end.
