### ISSUE TITLE
NPC names displayed on the map do not appear as their corresponding localized names

### ISSUE THREAD

**Issue by cainb** [bouhm/stardew-valley-mods#77]
Hi! Thank you very much for this mods! However, when I use the latest v2.6.2 version, I found that the NPC names displayed on the map are not displayed as their localized names, I remember that the previous version was able to display the localized names of the NPCs, am I remembering it wrong?

**Comment by Pathoschild** [comment]
Fixed in NPC Map Locations 2.6.3. Thanks for reporting it!
