### ISSUE TITLE
Minimap stuck on middle of screen

### ISSUE THREAD

**Issue by Alaska52127** [bouhm/stardew-valley-mods#86]
I'm not sure how it happened, I just left pierre's and closed my inventory. I must've pressed something by accident because the minimap moved to the middle of my screen. After searching online for a bit I found that I should be able to drag it by holding ctrl but it isn't moving. I use the minimap often so just leaving it off isn't desirable

**Comment by Pathoschild** [comment]
You can move the minimap by holding right-click on the minimap, dragging it to the new position, and releasing right-click to save. Recent versions also added an option to lock the minimap to avoid accidentally moving it.
