### ISSUE TITLE
[NPCMapLocations] Minimap showing NPCs outside it's border

### ISSUE THREAD

**Issue by KariArisu** [bouhm/stardew-valley-mods#98]
When using the minimap in the new version (2.9.2), NPCs are being shown outside of the Minimap UI window.
I'm using the smallest Minimap size, 75x45. Expanding the size in some cases makes it better, and in some makes it worse.

Picture below. :)

![image](https://user-images.githubusercontent.com/3825742/174427272-e011e7fd-8b1b-4415-b727-6a5532e7b03f.png)

**Comment by Pathoschild** [comment]
Thanks for reporting it! That should be fixed in NPC Map Locations 2.9.3. (Markers will still stick out past the edge a bit sometimes, like before. That'll be a bigger task to fix in later versions.)
